version: '3'

services:
  server:
    container_name: ListBotContainer
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db:
    image: 'mongo'
    container_name: MongoContainer
    environment:
      MONGO_INITDB_DATABASE: botlist
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db